

export const apis = {
    auth: 'auth/',
    api_categories: "categories/sorted-categories",
    api_brands: "brands",
    api_cities: 'cities',
    api_colors: 'colors',
    api_sizes: 'sizes',
    api_csrf: 'get-csrf',
    api_ads: "ads",
    api_upload: "upload",
    api_stats: "stats",
    api_store: "stores",
    api_messages: "messages",
    api_comment: "comments",
    api_fcm: "fcm",
    api_comment_status: "stats/comment-status/",
    api_lookup: "lookup",
    // test
    api_up: "cron",
    api_famous: "famous",
    api_packages: 'packages',
    api_update_store: 'stories/user/store',
    api_update_user: 'auth/user',
    api_banners: 'banners',
    api_contact: 'contact',
    api_deals: 'deals',
    api_rules: "rules",
    api_about: 'about',
    api_block: 'blocked',
    forgot_mobile: 'auth/forgot-mobile-password',
    ads_view_count: "stats/ads-view",
    ads_like_count: "stats/ads-like",
    api_payment: 'payment',
    api_check_order: 'payment/check-payment/',
    api_ads_search: "search",
    api_user_search: 'search/users?q=',
    api_influencers_search: 'search/users?type=influencer&q=',
    api_home: 'home/mobile',
    api_notification: 'notifications',
    api_users: "users/",
    api_influencers: "influencers/",
    api_version_control: "version-check",
}

