export type ProfileType = {

    _store: {
        _active_package: any,
        active_package_id: number,
        address: string,
        cover: string,
        createdAt: string,
        desc: string,
        email: string,
        end_hour: string,
        id: number,
        img: string,
        isRejected: boolean,
        name: string,
        orderNumber: number,
        phone: string,
        rejectReason: string,
        slug: string,

        social_links: {
            facebook: string,
            instagram: string,
            tiktok: string,

        },
        start_hour: string,
        status: boolean,
        updatedAt: string,
        user_id: number,
        verified: boolean,
        website: string,
        work_days: string,
    },
    cover: string,
    createdAt: string,
    email: string,
    facebookId: null,
    full_name: string,
    id: number,
    isActive: boolean,
    isAdmin: boolean,
    isFamous: boolean,
    isModer: boolean,
    isVip: boolean,
    is_inf: string,
    is_store: boolean,
    orderNumber: number,
    phone: string,
    phone_hide: boolean,
    photo: string,
    register_origin: string,
    secretBase32: null,
    shop_balance: number,
    social_links: {
        facebook: string,
        instagram: string,
    },
    sot: null,
    user_balance: number,
    username: string,
}